T8 BOLETÍN

1-	SELECT oficio, COUNT(*) AS 'NUM' FROM empleados GROUP BY oficio ORDER BY NUM DESC;

2-	SELECT asignatura, COUNT(*) AS 'Nº alumnos' FROM notas GROUP BY asignatura;

3-	SELECT alumno, AVG(NOTA) AS 'Media' FROM notas GROUP BY alumno;

4-	SELECT oficio FROM empleados GROUP BY OFICIO HAVING COUNT(*) > 2;

5-	SELECT IDDEPART FROM empleados GROUP BY IDDEPART HAVING COUNT(*) > 3;

6-	SELECT alumno, AVG(NOTA) AS 'media' FROM notas GROUP BY alumno HAVING AVG(NOTA) > 5.7 ORDER BY media ASC;

7-	SELECT oficio, SUM(SALARIO) AS 'media' FROM empleados GROUP BY OFICIO;

8-	SELECT oficio, SUM(SALARIO) FROM empleados GROUP BY OFICIO ORDER BY SUM(SALARIO) DESC LIMIT 1;

9-	SELECT OFICIO, AVG(SALARIO) FROM empleados GROUP BY OFICIO HAVING AVG(SALARIO) > 2000;

10-	SELECT IDDEPART, SUM(SALARIO) AS 'SUMA', MAX(SALARIO) AS 'MAXIMO', MIN(SALARIO) AS 'MINIMO' FROM empleados GROUP BY IDDEPART;

11-	SELECT IDDEPART, COUNT(*) AS 'numero' FROM empleados WHERE OFICIO = 'Empleado' GROUP BY IDDEPART;

12-	SELECT oficio, IDDEPART, COUNT(CODEMP) AS 'numero', SUM(SALARIO) AS 'suma' FROM empleados GROUP BY OFICIO, IDDEPART, OFICIO;

13-	SELECT IDDEPART, oficio, COUNT(CODEMP) AS  'numero' FROM empleados GROUP BY OFICIO, IDDEPART HAVING COUNT(OFICIO) > 2;

14-	SELECT IDDEPART, COUNT(distinct(oficio)) AS 'numero' FROM empleados GROUP BY IDDEPART;