2 SUBCONSULTAS

15-	SELECT CODEMP, APELLIDO FROM empleados WHERE IDDEPART =(SELECT IDDEPART from depart WHERE NOMBRE = 'Ventas');

16-	SELECT CODEMP, APELLIDO, salario FROM empleados WHERE salario>(SELECT salario from empleados WHERE CODEMP = 6);

17-	SELECT APELLIDO, OFICIO FROM EMPLEADOS WHERE OFICIO = (SELECT OFICIO FROM EMPLEADOS WHERE APELLIDO = 'Jimenez');

18-	SELECT APELLIDO, SALARIO FROM EMPLEADOS WHERE (OFICIO,SALARIO)=(SELECT OFICIO,SALARO FROM EMPLEADOS WHERE Apellido = 'Gil') 

19-	SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALT WHERE OFICIO=(SELECT OFICIO FROM EMPLEADOS WHERE APELLIDO ='Jimenez') OR WHERE SALARIO=(SELECT SALARIO FROM EMPLEADOS WHERE APELLIDO = 'Fernandez');

20.-	SELECT IDDEPART, COUNT(*) AS 'NUMERO' FROM empleados  WHERE OFICIO = (SELECT OFICIO FROM empleados WHERE OFICIO = 'Empleado' LIMIT 1) GROUP BY IDDEPART;

21.-	SELECT * FROM empleados WHERE SALARIO > (SELECT AVG(SALARIO) FROM empleados);

22.-	SELECT APELLIDO, SALARIO, OFICIO FROM empleados WHERE (IDDEPART, SALARIO) = (SELECT IDDEPART, SALARIO FROM empleados WHERE APELLIDO LIKE 'Fernandez') AND APELLIDO != 'Fernandez';

23.-	SELECT IDDEPART, AVG(SALARIO) AS 'MEDIA' FROM empleados  GROUP BY IDDEPART HAVING AVG(SALARIO) >=(SELECT AVG(SALARIO) FROM empleados);

24.-	SELECT IDDEPART, COUNT(*) AS 'numero' FROM empleados WHERE (IDDEPART,OFICIO) =(SELECT IDDEPART,OFICIO FROM depart WHERE Nombre = 'Ventas' AND OFICIO ='Vendedor');

25.-	SELECT APELLIDO, COMISION FROM empleados WHERE COMISION > (SELECT COMISION FROM empleados WHERE CODEMP = 3);

26.-	SELECT COUNT(*) AS 'NUMERO' FROM empleados  WHERE IDDEPART = (SELECT IDDEPART FROM depart WHERE NOMBRE LIKE 'Ventas') AND OFICIO = 'Director';

27.-	SELECT IDDEPART, MIN(SALARIO) AS 'SALARIO' FROM empleados WHERE IDDEPART != (SELECT IDDEPART FROM depart WHERE LOC LIKE 'Madrid') GROUP BY IDDEPART;

28.-	SELECT APELLIDO, IDDEPART FROM empleados WHERE IDDEPART IN (SELECT IDDEPART FROM depart WHERE LOC LIKE 'Madrid' OR LOC = 'Barcelona') ORDER BY IDDEPART;

29.-	SELECT IDDEPART, NOMBRE FROM depart GROUP BY IDDEPART HAVING IDDEPART NOT IN (SELECT IDDEPART FROM empleados WHERE COUNT(*) != 0);

30.-	SELECT APELLIDO, OFICIO, COMISION FROM empleados WHERE IDDEPART NOT IN (SELECT IDDEPART FROM depart WHERE LOC LIKE 'Madrid' OR LOC LIKE 'Sevilla') AND APELLIDO IN (SELECT APELLIDO FROM empleados WHERE COMISION IS NULL);

31.-	SELECT APELLIDO, OFICIO FROM empleados WHERE IDDEPART = 20 AND OFICIO IN (SELECT OFICIO from empleados WHERE IDDEPART = SELECT IDDEPART FROM depart WHERE NOMBRE = 'Ventas'));

32.-	SELECT NOMBRE FROM asignaturas WHERE COD IN (SELECT asignatura from notas WHERE NOTA > 5);

33.-	SELECT MAX(SALARIO) AS 'maximo', OFICIO FROM empleados WHERE IDDEPART IN(SELECT IDDEPART FROM depart WHERE Loc = 'Madrid' OR Loc = 'Sevilla') GROUP BY OFICIO HAVING AVG(SALARIO)< 4000; 	
	
34.-	SELECT IDDEPART, Nombre FROM depart WHERE IDDEPART IN (SELECT IDDEPART FROM empleados GROUP BY IDDEPART HAVING COUNT(*) > (SELECT COUNT(*) FROM empleados WHERE IDDEPART > 20)); 

35.-	SELECT apellido, salario, IDDEPART FROM empleados WHERE (IDDEPART,salario) IN (SELECT IDDEPART,MAX(salario) FROM empleados GROUP BY IDDEPART);

36.-	

37.-	

38.-	

39.-	

40.-
